@Api_HostAddress = http://localhost:5064

### Create user with ID
GET {{Api_HostAddress}}/command/create-user/123

### Create user for result
GET {{Api_HostAddress}}/command/create-user

### Update user with ID
GET {{Api_HostAddress}}/command/update-user/123

### Delete user with ID
GET {{Api_HostAddress}}/command/delete-user/123

### Get user by ID
GET {{Api_HostAddress}}/query/id/123
Accept: application/json

### Get user by name
GET {{Api_HostAddress}}/query/name/myname
Accept: application/json